name = "LinearCovarianceModels"
uuid = "4af8ee2a-afa9-11e9-10dc-fb1b37f8f4b5"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.2.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Distributions = "0.24"
HomotopyContinuation = "^2.3"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
